import jQuery from 'jquery';
import popper from 'popper.js';
import bootstrap from 'bootstrap';
import '../favicons/favicons';
import '../modules/resize';
import '../modules/lazy';
import '../modules/subscribe';
import '../scss/custom.scss';
import 'bootstrap/scss/bootstrap.scss';
import '../scss/main.scss';
